server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CatoriTech?currentSchema=public
    username: postgres
    password: 193192
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: user
  jpa:
    open-in-view: false